plugins {
    id 'fabric-loom' version '1.9-SNAPSHOT' apply false
    id 'base'
}

def nonMcSubprojects = [
        "mods"
]
def nonModSubprojects = [
        "mods",
        "dist"
]

//If you can think of a smarter way to remove a project from the Fabric Loom cache, feel free to rewrite this function.
ext.cleanRemappedSubprojectAt = {rDir, p ->
    var v = minecraft_version + "_" + yarn_mappings + "_${yarn_mappings_version}"
    v = v.replaceAll("\\.", "_").replaceAll("\\+", "_")
    var g = p.maven_group.replaceAll("\\.", "/")
    delete(project.file("${rDir}/.gradle/loom-cache/remapped_mods/net_fabricmc_yarn_${v}/${g}/${p.name}"))
}

ext.cleanRemappedSubproject = {p ->
    cleanRemappedSubprojectAt(rootDir, p)
}

project.runMode = hasProperty("run-mode")

// For all modules that are fabric mods (all mods and dist)
subprojects {
    if (nonMcSubprojects.contains(it.name)) {
        return
    }
    clean.doFirst {
        rootProject.runMode = false
    }
    apply plugin: "fabric-loom"
    runClient.doFirst {
        rootProject.runMode = true
    }
    if (project.tasks.findByName('runDatagen') != null) {
        runDatagen.doFirst {
            rootProject.runMode = true
        }
    }
    runServer.doFirst {
        rootProject.runMode = true
    }

    ext.dependIfPossible = {Project dep ->
        dependencies {
            //modImplementation fails if the library has not been built.
            //But we still need to use it for the runtime environment to work.
            //When it's not present, we use implementation instead so we can at least compile.
            if (dep.file("build/libs").exists() && rootProject.runMode) {
                modImplementation dep
            } else {
                implementation dep
            }
        }
    }

    ext.addProjectDependency = {dep ->
        var p = project(dep)
        dependIfPossible(p)

        compileJava {
            cleanRemappedSubprojectAt(
                    project.layout.projectDirectory, p
            )
        }
    }

    ext.addLeukocyteDependency = { ->
        dependencies {
            //It is slow to update so we usually want it set to modCompileOnly.
            modCompileOnly("maven.modrinth:leukocyte:${project.leukocyte_version}")
        }
    }

    ext.addSGUIDependency = { ->
        dependencies {
            modImplementation("eu.pb4:sgui:${project.sgui_version}")
        }
    }

    ext.addPolymerDependency = { ->
        dependencies {
            modImplementation("eu.pb4:polymer-core:${project.polymer_version}")
        }
    }

    ext.addVanishDependency = { ->
        dependencies {
            modImplementation "maven.modrinth:vanish:${project.vanish_version}"
            modImplementation "eu.pb4:player-data-api:${project.player_data_api_version}" //Dependency for Vanish.
            modImplementation("eu.pb4:placeholder-api:${project.placeholder_api_version}") //Dependency for Vanish.
        }
    }

    group = project.maven_group

    def targetJavaVersion = 21
    tasks.withType(JavaCompile).configureEach {
        // ensure that the encoding is set to UTF-8, no matter what the system default is
        // this fixes some edge cases with special characters not displaying correctly
        // see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
        // If Javadoc is generated, this must be specified in that task too.
        it.options.encoding = "UTF-8"
        if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
            it.options.release.set(targetJavaVersion)
        }
    }

    java {
        def javaVersion = JavaVersion.toVersion(targetJavaVersion)
        if (JavaVersion.current() < javaVersion) {
            toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
        }
        // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
        // if it is present.
        // If you remove this line, sources will not be generated.
        withSourcesJar()
    }

    jar {
        from("LICENSE") {
            rename { "${it}_${project.name}"}
        }
    }

    processResources {
        inputs.property "version", project.version
        inputs.property "minecraft_version", project.minecraft_version
        inputs.property "loader_version", project.loader_version
        filteringCharset "UTF-8"

        filesMatching("fabric.mod.json") {
            expand "version": project.version,
                    "minecraft_version": project.minecraft_version,
                    "loader_version": project.loader_version,
                    "git_repo": project.git_repo,
                    "website": project.website,
                    "issues": project.issues
        }
    }

    dependencies {
        // To change the versions see the gradle.properties file
        minecraft "com.mojang:minecraft:${project.minecraft_version}"
        mappings "net.fabricmc:yarn:${project.yarn_mappings}:${project.yarn_mappings_version}"
        modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    }

    repositories {
        //Polymer
        maven { url 'https://maven.nucleoid.xyz' }

        //Leukocyte
        exclusiveContent {
            forRepository {
                maven {
                    name = "Modrinth"
                    url = "https://api.modrinth.com/maven"
                }
            }
            filter {
                includeGroup "maven.modrinth"
            }
        }
        maven { url = 'https://maven.nucleoid.xyz/' }

        //Mod Menu
        maven {
            url "https://maven.terraformersmc.com/"
        }

        maven { url 'https://jitpack.io' } // Fabric ASM
    }
}

// For all mods (but not dist)
subprojects {

    if (nonModSubprojects.contains(it.name)) {
        return
    }

    for (var s : gradle.startParameter.taskNames) {
        if (s.endsWith("test") || s.endsWith("build") || s.endsWith("runDatagen")) {
            rootProject.runMode = true
        }
    }

    base {
        archivesName = project.name
    }

    if (project.name != "metacraft-lib") {
        addProjectDependency(":mods:metacraft-lib")
    }

    dependencies {
        // Fabric API. This is technically optional, but you probably want it anyway.
        modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

        modImplementation("me.lucko:fabric-permissions-api:${project.fabric_permissions_api_version}")

        modImplementation("com.github.Chocohead:Fabric-ASM:${project.fabric_asm_version}")

        testImplementation "net.fabricmc:fabric-loader-junit:${project.loader_version}"

        modApi("com.terraformersmc:modmenu:${project.modmenu_version}"){
            exclude group: "net.fabricmc.fabric-api"
        }

        implementation("org.pcollections:pcollections:${project.pcollections_version}")
    }

    test {
        useJUnitPlatform()
    }

    //Cleans Fabric Loom cache on compilation.
    compileJava {
        cleanRemappedSubproject(project)
    }
}