plugins {
    id 'fabric-loom' version '1.8-SNAPSHOT' apply false
    id 'maven-publish'
    id 'base'
}

version = project.combined_version

evaluationDependsOnChildren()

def ignoredProjects = [
        "mods"
]

//If you can think of a smarter way to remove a project from the Fabric Loom cache, feel free to rewrite this function.
ext.cleanRemappedSubprojectAt = {rDir, p ->
    var v = minecraft_version + "_" + yarn_mappings + "_${yarn_mappings_version}"
    v = v.replaceAll("\\.", "_").replaceAll("\\+", "_")
    var g = p.maven_group.replaceAll("\\.", "/")
    delete(project.file("${rDir}/.gradle/loom-cache/remapped_mods/net_fabricmc_yarn_${v}/${g}/${p.name}"))
}

ext.cleanRemappedSubproject = {p ->
    cleanRemappedSubprojectAt(rootDir, p)
}

boolean skipRemap = hasProperty("skip-subproject-remap")

allprojects {
    if (ignoredProjects.contains(it.name)) {
        return
    }
    apply plugin: "fabric-loom"

    ext.dependIfPossible = {Project dep ->
        dependencies {
            //modImplementation fails if the library has not been built.
            //But we still need to use it for the runtime environment to work.
            //When it's not present, we use implementation instead so we can at least compile.
            if (dep.file("build/libs").exists() && !skipRemap) {
                modImplementation dep
            } else {
                implementation dep
            }
        }
    }

    ext.addProjectDependency = {dep ->
        var p = project(dep)
        dependIfPossible(p)

        compileJava {
            cleanRemappedSubprojectAt(
                    project.layout.projectDirectory, p
            )
        }
    }

    ext.addLeukocyteDependency = { ->
        dependencies {
            //It is slow to update so we usually want it set to modCompileOnly.
            modCompileOnly("maven.modrinth:leukocyte:${project.leukocyte_version}")
        }
    }

    ext.addSGUIDependency = { ->
        dependencies {
            modImplementation("eu.pb4:sgui:${project.sgui_version}")
        }
    }

    ext.addPolymerDependency = { ->
        dependencies {
            modImplementation("eu.pb4:polymer-core:${project.polymer_version}")
        }
    }

    ext.addVanishDependency = { ->
        dependencies {
            modImplementation "maven.modrinth:vanish:${project.vanish_version}"
            modImplementation "eu.pb4:player-data-api:${project.player_data_api_version}" //Dependency for Vanish.
            modImplementation("eu.pb4:placeholder-api:${project.placeholder_api_version}") //Dependency for Vanish.
        }
    }

    group = project.maven_group

    def targetJavaVersion = 21
    tasks.withType(JavaCompile).configureEach {
        // ensure that the encoding is set to UTF-8, no matter what the system default is
        // this fixes some edge cases with special characters not displaying correctly
        // see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
        // If Javadoc is generated, this must be specified in that task too.
        it.options.encoding = "UTF-8"
        if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
            it.options.release.set(targetJavaVersion)
        }
    }

    java {
        def javaVersion = JavaVersion.toVersion(targetJavaVersion)
        if (JavaVersion.current() < javaVersion) {
            toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
        }
        // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
        // if it is present.
        // If you remove this line, sources will not be generated.
        withSourcesJar()
    }

    jar {
        from("LICENSE") {
            rename { "${it}_${project.name}"}
        }
    }

    processResources {
        inputs.property "version", project.version
        inputs.property "minecraft_version", project.minecraft_version
        inputs.property "loader_version", project.loader_version
        filteringCharset "UTF-8"

        filesMatching("fabric.mod.json") {
            expand "version": project.version,
                    "minecraft_version": project.minecraft_version,
                    "loader_version": project.loader_version,
                    "git_repo": project.git_repo,
                    "website": project.website,
                    "issues": project.issues
        }
    }

    dependencies {
        // To change the versions see the gradle.properties file
        minecraft "com.mojang:minecraft:${project.minecraft_version}"
        mappings "net.fabricmc:yarn:${project.yarn_mappings}:${project.yarn_mappings_version}"
        modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    }

    repositories {
        //Polymer
        maven { url 'https://maven.nucleoid.xyz' }

        //Leukocyte
        exclusiveContent {
            forRepository {
                maven {
                    name = "Modrinth"
                    url = "https://api.modrinth.com/maven"
                }
            }
            filter {
                includeGroup "maven.modrinth"
            }
        }
        maven { url = 'https://maven.nucleoid.xyz/' }

        //Mod Menu
        maven {
            url "https://maven.terraformersmc.com/"
        }

        maven { url 'https://jitpack.io' } // Fabric ASM


        maven { url = uri("https://mvn.sigbla.app/repository") } //Persistent Data Structures
    }
}

subprojects {

    if (ignoredProjects.contains(it.name)) {
        return
    }

    base {
        archivesName = project.name
    }

    if (project.name != "metacraft-lib") {
        addProjectDependency(":mods:metacraft-lib")
    }

    dependencies {
        // Fabric API. This is technically optional, but you probably want it anyway.
        modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

        modImplementation("me.lucko:fabric-permissions-api:${project.fabric_permissions_api_version}")

        modImplementation("com.github.Chocohead:Fabric-ASM:${project.fabric_asm_version}")

        testImplementation('org.junit.jupiter:junit-jupiter:5.9.2')

        modApi("com.terraformersmc:modmenu:${project.modmenu_version}"){
            exclude group: "net.fabricmc.fabric-api"
        }

        implementation("sigbla.app:sigbla-pds:1.0")
    }

    test {
        useJUnitPlatform()
    }

    //Cleans Fabric Loom cache on compilation.
    compileJava {
        cleanRemappedSubproject(project)
    }
}

base {
    archivesName = project.archives_base_name
}

//We want this so launching the root project loads all the submodule mods.
//However, gradle can't find the file on first launch and will fail to parse the project.
//So we check if the libs folder exists.
subprojects.each {
    if (ignoredProjects.contains(it.name)) {
        return
    }
    dependIfPossible(it)
}

//Make sure the mods are bundled in the main release.
remapJar {
    afterEvaluate {
        subprojects.each {
            if (ignoredProjects.contains(it.name)) {
                return
            }
            nestedJars.from project("${it.path}").tasks.getByName("remapJar")
        }
    }
}


// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}
