									# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://modmuss50.me/fabric.html
	minecraft_version=1.21
	yarn_mappings=1.21+build.9
	yarn_mappings_version=v2
	loader_version=0.16.0

# Mod Properties
	combined_version = 1.0.0
	lib_version = 1.0.0
	core_version = 1.0.0
	zones_version = 1.0.0
	moderation_version = 1.0.0
	info_commands_version = 2.0.0
	blocker_version = 1.0.0
	maven_group = se.datasektionen.mc
	archives_base_name = metacraft

# Dependencies
	# check this on https://modmuss50.me/fabric.html
	fabric_version=0.100.7+1.21
	fabric_permissions_api_version=0.2-SNAPSHOT
	polymer_version=0.9.4+1.21
	stimuli_version=0.4.12+1.21
	leukocyte_version=0.3.8+1.20.6
	vanish_version=1.5.6+1.21
	player_data_api_version=0.6.0+1.21
	placeholder_api_version=2.4.0-pre.2+1.21


#Metadata
	git_repo=https://github.com/METAcraft-KTH/METAmods.git
	website=https://mc.datasektionen.se
	issues=https://github.com/METAcraft-KTH/METAmods/issues