									# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Fabric Properties
	# check these on https://modmuss50.me/fabric.html
	minecraft_version=1.21.3
	yarn_mappings=1.21.3+build.2
	yarn_mappings_version=v2
	loader_version=0.16.7

# Mod Properties
	combined_version = 1.0.0
	lib_version = 1.0.0
	core_version = 1.0.0
	zones_version = 1.0.0
	moderation_version = 1.0.0
	info_commands_version = 2.0.0
	portal_blocker_version = 1.0.0
	faster_minecarts_version = 1.0.0
	portable_jukebox_version = 1.0.0
	simple_custom_features_version = 1.0.0
	plots_version = 1.0.0
	loot_containers_version = 1.0.0
	saved_items_version = 1.0.0
	dungeons_version = 1.0.0
	weather_version = 1.0.0
	better_pets_version = 1.0.0
	cutscenes_version = 1.0.0
	portal_opening_version = 1.0.0
	resource_packs_version = 1.0.0
	season_4_version = 1.0.0
	maven_group = se.datasektionen.mc
	archives_base_name = metacraft

# Dependencies
	# check this on https://modmuss50.me/fabric.html
	fabric_version=0.106.1+1.21.3
	fabric_permissions_api_version=0.3.2
	fabric_asm_version=v2.3

	fiber_version=0.23.0-2
	modmenu_version=12.0.0-beta.1

	polymer_version=0.10.1+1.21.3
	sgui_version=1.7.2+1.21.2
	byte_buddy_version=1.14.4

	stimuli_version=0.5.0+1.21.3
	leukocyte_version=0.3.10+1.21.3
	vanish_version=1.5.8+1.21.3
	player_data_api_version=0.6.0+1.21
	placeholder_api_version=2.5.0+1.21.2
	squaremap_version=1.3.2-fabric,1.21.1


#Metadata
	git_repo=https://github.com/METAcraft-KTH/METAmods.git
	website=https://mc.datasektionen.se
	issues=https://github.com/METAcraft-KTH/METAmods/issues