pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
    }
}

include "dist"
include "mods:metacraft-core"
include "mods:metacraft-cutscenes"
include "mods:metacraft-lib"
include "mods:metacraft-minigame-util"
include "mods:metacraft-moderation"
include "mods:metacraft-pause"
include "mods:metacraft-player-specific-scoreboards"
include "mods:metacraft-resource-packs"
include "mods:metacraft-zones"
include "mods:point-system"

