pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
    }
}

include "dist"
include "mods:better-pets"
include "mods:discord-chat-fixer"
include "mods:faster-minecarts"
include "mods:metacraft-core"
include "mods:metacraft-cutscenes"
include "mods:metacraft-dungeons"
include "mods:metacraft-info-commands"
include "mods:metacraft-lib"
include "mods:metacraft-loot-containers"
include "mods:metacraft-moderation"
include "mods:metacraft-plots"
include "mods:metacraft-resource-packs"
include "mods:metacraft-saved-items"
include "mods:metacraft-season-4"
include "mods:metacraft-weather"
include "mods:metacraft-zones"
include "mods:portable-jukebox"
include "mods:portal-blocker"
include "mods:simple-custom-features"

