pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
    }
}

include "dist"
include "mods:better-pets"
include "mods:discord-chat-fixer"
include "mods:faster-minecarts"
include "mods:metacraft-bosses"
include "mods:metacraft-bundles"
include "mods:metacraft-core"
include "mods:metacraft-cutscenes"
include "mods:metacraft-dungeons"
include "mods:metacraft-relay"
include "mods:metacraft-repair-fix"
include "mods:metacraft-info-commands"
include "mods:metacraft-lib"
include "mods:metacraft-loot-containers"
include "mods:metacraft-minigame-util"
include "mods:metacraft-moderation"
include "mods:metacraft-plots"
include "mods:metacraft-fake-player-blocker"
include "mods:metacraft-resource-packs"
include "mods:metacraft-revival"
include "mods:metacraft-saved-items"
include "mods:metacraft-season-5"
include "mods:metacraft-weather"
include "mods:metacraft-zones"
include "mods:point-system"
include "mods:portable-jukebox"
include "mods:portal-blocker"
include "mods:simple-custom-features"

