version = project.lib_version

loom {
	accessWidenerPath = file("src/main/resources/metacraft_lib.accesswidener")
}

dependencies {
	include("me.lucko:fabric-permissions-api:${project.fabric_permissions_api_version}")
	include("com.github.Chocohead:Fabric-ASM:${project.fabric_asm_version}")
}

addVanishDependency()