version = project.season_4_version

addCoreDependencies()
addProjectDependency(":mods:metacraft-bosses")
addProjectDependency(":mods:metacraft-cutscenes")
addLeukocyteDependency()

loom {
	accessWidenerPath = file("src/main/resources/metacraft_season_4.accesswidener")
}

setupRunDatagen("metacraft-season-4")

dependencies {
	modCompileOnly("xyz.nucleoid:stimuli:${project.stimuli_version}")
	modImplementation("eu.pb4:polymer-virtual-entity:${project.polymer_version}")
	implementation("org.objenesis:objenesis:${project.objenesis_version}")
}
