version = project.season_4_version

addProjectDependency(":mods:metacraft-core")
addLeukocyteDependency()
addPolymerDependency()

loom {
	accessWidenerPath = file("src/main/resources/metacraft_season_4.accesswidener")
}

fabricApi {
	configureDataGeneration{
		client = true
	}
}

dependencies {
	modCompileOnly("xyz.nucleoid:stimuli:${project.stimuli_version}")
	modImplementation("eu.pb4:polymer-virtual-entity:${project.polymer_version}")
}
