version = project.portable_jukebox_version

loom {
	accessWidenerPath = file("src/main/resources/portable_jukebox.accesswidener")
}

addPolymerDependency()
addSGUIDependency()

dependencies {
	modImplementation("maven.modrinth:lithium:$lithium_version-fabric")
	modCompileOnly("maven.modrinth:ledger:$ledger_version")
}