version = project.portable_jukebox_version

loom {
	accessWidenerPath = file("src/main/resources/portable_jukebox.accesswidener")
}

addPolymerDependency()
addSGUIDependency()

dependencies {
	implementation("maven.modrinth:lithium:$lithium_version-fabric")
	compileOnly("maven.modrinth:ledger:$ledger_version")
}