version = project.zones_version

addCoreDependencies()
addProjectDependency(":mods:metacraft-resource-packs")
addLeukocyteDependency()

loom {
	accessWidenerPath = file("src/main/resources/metacraft_zones.classtweaker")
}

dependencies {
	compileOnly("xyz.nucleoid:stimuli:${project.stimuli_version}")
}
