version = project.cutscenes_version

loom {
	accessWidenerPath = file("src/main/resources/metacraft_cutscenes.accesswidener")
}

addCoreDependencies()
addProjectDependency(":mods:metacraft-resource-packs")

dependencies {
	implementation(include("org.objenesis:objenesis:${project.objenesis_version}"))
}
