version = project.cutscenes_version

loom {
	accessWidenerPath = file("src/main/resources/metacraft_cutscenes.accesswidener")
}

addProjectDependency(":mods:metacraft-core")
addProjectDependency(":mods:metacraft-resource-packs")
addPolymerDependency()

dependencies {
	implementation(include('org.objenesis:objenesis:3.4'))
}